**Kütüphanelerin Eklenmesi**

In [22]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from word2number import w2n

**Verinin Excel Dosyasından Okunması**

In [23]:
# Verimizi excel dosyası içerisinden alıyoruz. 
veri = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/Lineer Regresyon/Maaş Tahmini/maas.xlsx")
veri

deneyim  teknikmulakat  sozelmulakat   maas
0     NaN            8.0             9  50000
1     NaN            8.0             6  45000
2    five            6.0             7  60000
3     two           10.0            10  65000
4   seven            9.0             6  70000
5   three            7.0            10  62000
6     ten            NaN             7  72000
7  eleven            7.0             8  80000

**Veri Ön İşleme**


In [24]:
# Deneyim sütunu içerisinde yer alan boşlukları dolduruyoruz.
veri.deneyim = veri.deneyim.fillna("zero")
veri

deneyim  teknikmulakat  sozelmulakat   maas
0    zero            8.0             9  50000
1    zero            8.0             6  45000
2    five            6.0             7  60000
3     two           10.0            10  65000
4   seven            9.0             6  70000
5   three            7.0            10  62000
6     ten            NaN             7  72000
7  eleven            7.0             8  80000

In [25]:
# Deneyim sütunu içerisinde yer alan değerleri sayıya çeviriyoruz.
veri.deneyim = veri.deneyim.apply(w2n.word_to_num)
veri

deneyim  teknikmulakat  sozelmulakat   maas
0        0            8.0             9  50000
1        0            8.0             6  45000
2        5            6.0             7  60000
3        2           10.0            10  65000
4        7            9.0             6  70000
5        3            7.0            10  62000
6       10            NaN             7  72000
7       11            7.0             8  80000

In [26]:
# Teknik mülakat puanı içerisinde yer alan boşlukları doldurmak için puan medyanını hesaplıyoruz.
import math
medyan_teknik = math.floor(veri['teknikmulakat'].mean())
medyan_teknik

7

In [27]:
# Teknik mülakat sütunu içerisinde yer alan boşlukları dolduruyoruz.
veri['teknikmulakat'] = veri['teknikmulakat'].fillna(medyan_teknik)
veri

deneyim  teknikmulakat  sozelmulakat   maas
0        0            8.0             9  50000
1        0            8.0             6  45000
2        5            6.0             7  60000
3        2           10.0            10  65000
4        7            9.0             6  70000
5        3            7.0            10  62000
6       10            7.0             7  72000
7       11            7.0             8  80000

In [28]:
# Verimiz kullanıma hazır :)

**Lineer Regresyon Modelinin Oluşturulması**

In [29]:
# Modelimizi elimizdeki verileri kullanarak eğitiyoruz.
model = linear_model.LinearRegression()
model.fit(veri[['deneyim','teknikmulakat','sozelmulakat']],veri['maas'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [30]:
# Modelimize tabloda bulunan bir veri kontrol amaçlı verildiğinde modelin yakın bir tahmin gerçekleştirdiği görülmektedir.
model.predict([[0,8,9]])

array([52090.46734071])

In [31]:
# Maaş tahmini örneği
model.predict([[2,9,6]])

array([53713.86677124])

In [32]:
# m1.x1 + m2.x2 + m3.x3 + b = y
# Lineer regresyon modelinin ağırlık değerleri
model.coef_

array([2922.26901502, 2221.30909959, 2147.48256637])

In [33]:
# Lineer regresyon modelinin sabit değeri
model.intercept_

14992.65144669314